### ISSUE TITLE
Please upgrade to node-20

### ISSUE THREAD

**Issue by berryware** [livewing/lcov-job-summary#47]
Thanks for taking the time to create this action. It is very useful. 

Please upgrade your action to use node-20 as node-16 is being deprecated. 

[Coverage (ubuntu-latest, nightly)](https://github.com/exaxisllc/cl_parse/actions/runs/9700615258/job/26772427623)
Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: livewing/lcov-job-summary@v1.1.0, bigmeech/gha-simple-coverage@master. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.

**Comment by livewing** [comment]
I apologize for my delayed response.

Thank you for letting me know. I will upgrade the Node.js to v20.
